// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnngvprkerwxkpyvwlkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZubmd2cHJrZXJ3eGtweXZ3bGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDI2NDEsImV4cCI6MjA2NTQxODY0MX0.a8vzkKjYn4cLkBirTb2ghedI9Rbwc4aIaGsZrAY1BuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);